<<<<<<< HEAD
=======

>>>>>>> b792bee (Corrigindo pipeline CI/CD no GitHub Actions)
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
<<<<<<< HEAD
          python-version: "3.9"
=======
          python-version: '3.9'
>>>>>>> b792bee (Corrigindo pipeline CI/CD no GitHub Actions)

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar Testes
        run: pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para Produção
<<<<<<< HEAD
        run: echo "Deploy realizado com sucesso!"

=======
        run: echo 'Deploy realizado com sucesso!'
>>>>>>> b792bee (Corrigindo pipeline CI/CD no GitHub Actions)

